/**************************************
    Webutler V3.2 - www.webutler.de
    Copyright (c) 2008 - 2016
    Autor: Sven Zinke
    Free for any use
    Lizenz: GPL
**************************************/
function loadTreeHTML(bgimgpath,editor)
{var selectBox='';for(var i=0;i<InternPagesSelectBox.length;i++){var item=InternPagesSelectBox[i];if(typeof item[1]==='object'){selectBox+='<optgroup label="'+CKEDITOR.tools.htmlEncode(item[0])+'">';for(var k=0;k<item[1].length;k++){var opt=item[1][k];selectBox+='<option'+
CKEDITOR.tools.htmlEncode(opt[2]!==undefined?' '+opt[2]:'')+' value="'+CKEDITOR.tools.htmlEncode(opt[1]!==undefined?opt[1]:opt[0]).replace(/"/g,'&quot;')+'">'+
CKEDITOR.tools.htmlEncode(opt[0])+'</option>';}
selectBox+='</optgroup>';}
else{selectBox+='<option'+' value="'+CKEDITOR.tools.htmlEncode(item[1]!==undefined?item[1]:item[0]).replace(/"/g,'&quot;')+'">'+
CKEDITOR.tools.htmlEncode(item[0])+'</option>';}}
var TreeHTML='<div style="display: none" id="treemenu_savedMenu"></div>'+'<div style="display: none" id="treemenu_subDiv"></div>'+'<div style="display: none" id="treemenu_newMenu"></div>'+'<div id="DynamicTreebuilder">'+'<table border="0" cellspacing="0" cellpadding="0">'+'<tr>'+'<td valign="top">'+'<div class="actions">'+'<table border="0" cellspacing="0" cellpadding="0">'+'<tr>'+'<td><input type="button" class="moveIt" onclick="treeMoveUp()" style="background-image: url('+bgimgpath+'moveup.png)" title="'+editor.lang.sortmenu.posup+'" /></td>'+'<td><input type="button" class="moveIt" onclick="treeMoveDown()" style="background-image: url('+bgimgpath+'movedown.png)" title="'+editor.lang.sortmenu.posdown+'" /></td>'+'<td><input type="button" class="moveIt" onclick="treeMoveLeft()" style="background-image: url('+bgimgpath+'moveleft.png)" title="'+editor.lang.sortmenu.posout+'" /></td>'+'<td><input type="button" class="moveIt" onclick="treeMoveRight()" style="background-image: url('+bgimgpath+'moveright.png)" title="'+editor.lang.sortmenu.posin+'" /></td>'+'<td><input type="button" class="action" onclick="treeInsert()" style="background-image: url('+bgimgpath+'plus.png)" title="'+editor.lang.sortmenu.insert+'" /></td>'+'<td><input type="button" class="action" onclick="treeRemove()" style="background-image: url('+bgimgpath+'delete.png)" title="'+editor.lang.sortmenu.delete+'" /></td>'+'</tr>'+'</table>'+'</div>'+'<div id="tree-insert" class="insertnew">'+'<div id="tree-insert-form">'+'<table border="0" cellspacing="0" cellpadding="0">'+'<tr>'+'<td colspan="2"><strong>'+editor.lang.sortmenu.new.add+'</strong></td>'+'</tr>'+'<tr>'+'<td>'+editor.lang.sortmenu.new.name+':</td>'+'</tr>'+'<tr>'+'<td><input type="text" id="tree-insert-name" class="field" /></td>'+'</tr>'+'<tr>'+'<td>'+editor.lang.sortmenu.new.link+':</td>'+'</tr>'+'<tr>'+'<td><input type="text" id="tree-insert-href" class="field" /></td>'+'</tr>'+'<tr>'+'<td>'+editor.lang.sortmenu.new.page+':</td>'+'</tr>'+'<tr>'+'<td>'+'<select id="tree-select-page" class="select" onchange="setPageToURL()">'+
selectBox+'</select>'+'</td>'+'</tr>'+'<tr>'+'<td colspan="2" class="center">'+'<input type="button" class="button" onclick="treeInsertExecute(\''+encodeURIComponent(editor.lang.sortmenu.fieldsnotempty)+'\')" value="'+editor.lang.sortmenu.insert+'" />'+'<input type="button" class="button" onclick="treeCancelNew()" value="'+editor.lang.sortmenu.close+'" />'+'</td>'+'</tr>'+'</table>'+'</div>'+'</div>'+'<div class="menusorter">'+'<div style="margin: 5px; padding: 0">'+'<div class="top">Treemen&uuml;</div>'+'<div id="treemenubuilder">'+'</div>'+'</div>'+'</div>'+'</div>'+'</td>'+'</tr>'+'</table>'+'</div>';return TreeHTML;}