/**************************************
    Webutler V3.2 - www.webutler.de
    Copyright (c) 2008 - 2016
    Autor: Sven Zinke
    Free for any use
    Lizenz: GPL
**************************************/
'use strict';(function()
{CKEDITOR.plugins.add('pastedupload',{requires:'uploadwidget',init:function(editor)
{if(!CKEDITOR.plugins.clipboard.isFileApiSupported){return;}
CKEDITOR.document.appendStyleSheet(this.path+'pastedupload.css');CKEDITOR.scriptLoader.load(this.path+'options.php');var loadingImage='data:image/gif;base64,R0lGODlhDgAOAIAAAAAAAP///yH5BAAAAAAALAAAAAAOAA4AAAIMhI+py+0Po5y02qsKADs=';var optionsPopup;var imageAttributes={};var fileUrl;var fileTools=CKEDITOR.fileTools;var uploadUrl=fileTools.getUploadUrl(editor.config,'image');var loaders={};if(!uploadUrl){window.console&&window.console.log('Error: Upload URL for the Upload Image feature was not defined. '+'For more information see: http://docs.ckeditor.com/#!/guide/dev_file_upload');return;}
fileTools.addUploadWidget(editor,'imagepasted',{loadMethod:'load',parts:{img:'img'},onLoaded:function(upload){this.parts.img.setAttribute('src',upload.data);},onUploaded:function(upload){var imgSource='<img src="'+upload.url+'" ';for(var key in imageAttributes){if(key=='width'||key=='height'){if(editor.config.image_prefillDimensions){imgSource+=key+'="'+imageAttributes[key]+'" ';}}
else{imgSource+=key+'="'+imageAttributes[key]+'" ';}}
imgSource+='/>';this.replaceWith(imgSource);}});editor.on('paste',function(evt){var data=evt.data,dataTransfer=data.dataTransfer,filesCount=dataTransfer.getFilesCount();if(data.dataValue||!filesCount){return;}
for(var i=0;i<filesCount;i++){var file=dataTransfer.getFile(i);if(fileTools.isTypeSupported(file,/image\/(jpeg|png|gif)/)){var el=new CKEDITOR.dom.element('img');el.setAttribute('src',loadingImage);loaders[i]=editor.uploadRepository.create(file);if(el){loaders[i].load();fileTools.markElement(el,'imagepasted',loaders[i].id);data.dataValue+=el.getOuterHtml();}}}
if(!data.dataValue.match(/<img[\s\S]+data:/i)){return;}
optionsPopup=new CKEDITOR.dom.element('div');optionsPopup.setAttributes({'class':'cke_reset_all cke_upload_options'});optionsPopup.setHtml(popupSource);CKEDITOR.document.getBody().append(optionsPopup);document.getElementById('cke_pastedupload_button').onclick=function(){editor.widgets.registered.imagepasted.loadMethod='upload';var filepath=document.getElementById('cke_pastedupload_filepath').value;var overwrite=document.getElementById('cke_pastedupload_overwrite').checked==true?'true':'false';var smallwidth=document.getElementById('cke_pastedupload_imgsmallwidth').value;var smallheight=document.getElementById('cke_pastedupload_imgsmallheight').value;var boxwidth=document.getElementById('cke_pastedupload_imgboxwidth').value;var boxheight=document.getElementById('cke_pastedupload_imgboxheight').value;var lightbox=document.getElementById('cke_pastedupload_lightbox').checked==true?'true':'false';fileUrl='&actualfolder='+encodeURIComponent('/'+filepath+'/');fileUrl+='&overwrite='+overwrite;fileUrl+='&imgsmallwidth='+parseInt(smallwidth);fileUrl+='&imgsmallheight='+parseInt(smallheight);fileUrl+='&imgboxwidth='+parseInt(boxwidth);fileUrl+='&imgboxheight='+parseInt(boxheight);fileUrl+='&lightbox='+lightbox;optionsPopup.remove();for(var key in loaders){var filename=loaders[key].fileName;fileUrl+='&filename='+encodeURIComponent(filename);loaders[key].upload(uploadUrl+fileUrl);fileTools.bindNotifications(editor,loaders[key]);}}},null,null,11);editor.on('fileUploadRequest',function(evt){var fileLoader=evt.data.fileLoader;var xhr=fileLoader.xhr;xhr.open('POST',fileLoader.uploadUrl,true);xhr.setRequestHeader('Cache-Control','no-cache');xhr.setRequestHeader('X-File-Name',fileLoader.fileName);xhr.setRequestHeader('X-File-Size',fileLoader.total);xhr.send(fileLoader.file);evt.stop();},null,null,1);editor.on('fileUploadResponse',function(evt){evt.stop();var data=evt.data,xhr=data.fileLoader.xhr;try{var response=JSON.parse(xhr.responseText);if(response.uploaded==1){imageAttributes=response.attributes;data.url=response.url;if(response.error)
alert(response.error.message);}
else{if(response.error)
data.message=response.error.message;evt.cancel();}}catch(err){data.message=fileLoader.lang.filetools.responseError;window.console&&window.console.log(xhr.responseText);evt.cancel();}},null,null,1);}});})();